### PR TITLE
Add encoding properties.

### PR DESCRIPTION
**Pull request by greut**
See: github.com/herrstucki/swiss-maps#18

### CODE REVIEW

**Comment by jstcki** [comment]
Thanks! I think it would probably be a good idea to make `"utf8"` the default instead of `null` (does it even work with `null`?).

This would also be a good opportunity to add a few tests :grin:.

**Comment by greut** [comment]
`null` falls back to the default behaviour of shapefile. See: https://github.com/mbostock/shapefile/blob/b4470c9a3d121bd201ca0b458d1e97b0a4d3547f/dbf.js#L9

**Comment by greut** [comment]
The tests are directly using the files from shapefile. It's not super nice but proves that the encoding argument is indeed needed.

Cheers!

**Comment by jstcki** [comment]
Woah, great! Thanks!

We can improve the tests when they fail :smile:

**Pull request merged**
